### ISSUE TITLE
Conflicting license information?

### ISSUE THREAD

**Issue by fmeum** [PeculiarVentures/ByteStream.js#1]
I am currently working on packaging an app depending on PKIjs (and thus ByteStream.js) for distribution. As this would happen in minified form, I want to ensure all licensing and usage requirements are fulfilled. 

While looking through all of PKIjs dependencies, I noted that the licensing of ByteStream.js appears to be a bit unclear: While the [LICENSE file](https://github.com/PeculiarVentures/ByteStream.js/blob/master/LICENSE) clearly states the source code can be freely redistributed as long as the license and disclaimer are preserved, [this comment](https://github.com/PeculiarVentures/ByteStream.js/blob/b43a506b01b9da5f70f9ac0e516e878e26ae4f29/src/bytestream.js#L7) seemingly makes it impossible to distribute ByteStream.js (or even to clone the repo, if taken literally).

I would be very glad if you could clarify the situation or even go as far as stating your favourite way of distributing minifed versions of PKIjs in a legally sound manner.

**Comment by YuryStrozhevsky** [comment]
@FabianHenneke It is "an artifact" from initially private development. I have removed it.
